<?php
namespace webapp\model;
/**
* 
*/
class Expense
{
	private $expId;
	private $category;
	private $item;
	private $amount;
	private $dateOfEntry;
	private $dateIncurred;
	private $userId;
	private $householdId; 
	private $type; //personal or household
	
	function __construct()
	{
		# code...
	}

	/************************************************************
	*createExpense($elements): This function create an expense object with 
	*				  default attribute values passed to its parameter (factory function)
	*
	*Parameters:
	*	$arrayOfElements: This is an associated array of Expense elements 
	*/
	public static function createExpense($arrayOfElements){
		$expense = new Expense();
	
		//TODO: HouseholdID and userID will be retrieved from database and/or SESSION. 
		//TODO: DataOfEntry shall be automated using the php data/time function. 
		//TODO:expenseID will be auto generated by database

		//$expense->setId($arrayOfElements['expId']);
		$expense->setCategory($arrayOfElements['category']);
		$expense->setAmount($arrayOfElements['amount']);
		$expense->setItem($arrayOfElements['item']);
		//$expense->setHouseholdId($arrayOfElements['householdId']); 
		//$expense->setUserId($arrayOfElements['userId']);
		$expense->setDateIncurred($arrayOfElements['dateIncurred']);
		$expense->setExpType($arrayOfElements['type']);
		//$expense->setDateOfEntry($arrayOfElements['dateOfEntry']); //this should be set by default by the database rule
		return $expense; 
	}//createExpense() Ends 


	/**Define getter function */
	function getId(){
		return $this->expId; 
	}

	function getItem(){
		return $this->item; 
	}

	function getCategory(){
		return $this->category;
	}

	function getAmount(){
		return $this->amount; 
	}

	function getDateOfEntry(){
		return $this->dateOfEntry;
	}
	function getDateIncurred(){
		return $this->dateIncurred;
	}
	function getUserId(){
		return $this->userId;
	}
	function getHouseholdId(){
		return $this->householdId;
	}
	function getExpType(){
		return $this->type; 
	}

	/**Define setter functions*/
	function setId($expId){
		 $this->expId = $expId; 
	}

	function setCategory($category){
		$this->category = $category;
	}

	function setAmount($amount){
		$this->amount = $amount; 
	}

	function setDateOfEntry($dateOfEntry){
		$this->dateOfEntry = $dateOfEntry; 
	}
	function setDateIncurred($dateIncurred){
		$this->dateIncurred = $dateIncurred; 
	}
	function setUserId($userId){
		$this->userId = $userId; 
	}
	function setHouseholdId($householdId){
		$this->householdId = $householdId; 
	}
	function setExpType($expenseType){
		$this->type = $expenseType;  
	}

	function setItem($item){
		$this->item = $item;  
	}


}//Expense class Ends 

?>